name: build
run-name: "Create release ${{ github.version }}"
on:
  push:
    tags:
      - '*'
jobs:
  create-shasums:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          sha512sum cipherguard-repo-setup.ce.sh > cipherguard-ce-SHA512SUM.txt
          sha512sum cipherguard-repo-setup.pro.sh > cipherguard-pro-SHA512SUM.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "cipherguard-repo-*, *SHA512SUM.txt"
